### ISSUE TITLE
tableName field is not used for the table name

### ISSUE THREAD

**Issue by aahdahl** [aheissenberger/sam-dyamodb-create-table#1]
The TableName field in the cloudformation template is not used as the table name when the table is created with this library, instead the resource name is used as a table name.

**Comment by aahdahl** [comment]
@aheissenberger: if you give me access, i can provide you with a pr for fixing this issue, it is pretty straight forward (and would render this module pretty useful when using custom, non-generated table names).

**Comment by aheissenberger** [comment]
is included in latest version
